### ISSUE TITLE
example XC in readme, python version

### ISSUE THREAD

**Issue by NoldAndreas** [verzep/finder_code#1]
Hi Pietro, 
in the readme, maybe we can have an example that runs straight away (i.e. define some example XC). 
I tried to run it one a small white noise sample: 

`from finder import Finder
import numpy as np

XC = np.random.rand(100, 2)

FD      = Finder()
labels  = FD.fit(XC)
result_ = FD.selected_parameters`

But there was some issue with numpy (AttributeError: module 'numpy' has no attribute 'int'.), ie probably a version issue. Which python version did you test it on? (The current environment I was testing it in was using the old Python 3.8.11).

**Comment by verzep** [comment]
For me that code is working, i have

Python 3.9
numpy 1.22.3

**Comment by verzep** [comment]
ok I installed the more recent version of numpy and now I get the same error, I will fix it.

**Comment by verzep** [comment]
I removed the deprecated 'np.int' instances, now it should work also for the recent version of numpy
